FROM golang:1.17.0-alpine AS builder

WORKDIR /build
COPY ./go.* ./
RUN go mod download
COPY . .
RUN go build -o api

FROM alpine

COPY --from=builder /build/api /
EXPOSE $API_PORT
ENV MONGODB_URI=$MONGODB_URI \
    MONGODB_NAME=$MONGODB_NAME \
    MONGODB_MICOL=$MONGODB_MICOL \
    MONGODB_AGCOL=$MONGODB_AGCOL \
    MONGODB_PKGCOL=$MONGODB_PKGCOL \
    MONGODB_REVCOL=$MONGODB_REVCOL \
    DADOSJUSBR_ENV=$DADOSJUSBR_ENV \
    DADOSJUS_URL=$DADOSJUS_URL \
    PACKAGE_REPO_URL=$PACKAGE_REPO_URL \
    SEARCH_LIMIT=$SEARCH_LIMIT \
    DOWNLOAD_LIMIT=$DOWNLOAD_LIMIT \
    PG_PORT=$PG_PORT \
    PG_HOST=$PG_HOST \
    PG_DATABASE=$PG_DATABASE \
    PG_USER=$PG_USER \
    PG_PASSWORD=$PG_PASSWORD \
    API_PORT=$API_PORT
CMD ["/api"]