// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "DadosJusBr",
            "url": "https://dadosjusbr.org"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/orgao/{orgao}": {
            "get": {
                "description": "Busca um órgão específico utilizando sua Unidade Federativa.",
                "produces": [
                    "application/json"
                ],
                "operationId": "getAgencyById",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID do órgão. Exemplos: al, ba, df.",
                        "name": "orgao",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Requisição bem sucedida.",
                        "schema": {
                            "$ref": "#/definitions/responses.Agency"
                        }
                    },
                    "404": {
                        "description": "Órgão não encontrado.",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "responses.Agency": {
            "type": "object",
            "properties": {
                "aid": {
                    "type": "string"
                },
                "collecting": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/responses.Collecting"
                    }
                },
                "entity": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "uf": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "responses.Collecting": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API do dadosjusbr.org",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
