definitions:
  papi.agency:
    properties:
      coletando:
        items:
          $ref: '#/definitions/papi.collecting'
        type: array
      entidade:
        description: '"J" For Judiciário, "M" for Ministério Público, "P" for Procuradorias
          and "D" for Defensorias.'
        type: string
      id_orgao:
        description: '''trt13'''
        type: string
      jurisdicao:
        description: '"R" for Regional, "M" for Municipal, "F" for Federal, "E" for
          State.'
        type: string
      nome:
        description: '''Tribunal Regional do Trabalho 13° Região'''
        type: string
      ouvidoria:
        description: Agencys's ombudsman url
        type: string
      twitter_handle:
        description: Agency's twitter handle
        type: string
      uf:
        description: Short code for federative unity.
        type: string
      url:
        description: Link for state url
        type: string
    type: object
  papi.collecting:
    properties:
      descricao:
        description: Reasons why we didn't collect the data
        items:
          type: string
        type: array
      timestamp:
        description: Day(unix) we checked the status of the data
        type: integer
    type: object
  uiapi.agency:
    properties:
      coletando:
        items:
          $ref: '#/definitions/uiapi.collecting'
        type: array
      entidade:
        description: '"J" For Judiciário, "M" for Ministério Público, "P" for Procuradorias
          and "D" for Defensorias.'
        type: string
      id_orgao:
        description: '''trt13'''
        type: string
      jurisdicao:
        description: '"R" for Regional, "M" for Municipal, "F" for Federal, "E" for
          State.'
        type: string
      nome:
        description: '''Tribunal Regional do Trabalho 13° Região'''
        type: string
      ouvidoria:
        description: Agencys's ombudsman url
        type: string
      twitter_handle:
        description: Agency's twitter handle
        type: string
      uf:
        description: Short code for federative unity.
        type: string
      url:
        description: Link for state url
        type: string
    type: object
  uiapi.backup:
    properties:
      hash:
        type: string
      size:
        type: integer
      url:
        type: string
    type: object
  uiapi.collecting:
    properties:
      descricao:
        description: Reasons why we didn't collect the data
        items:
          type: string
        type: array
      timestamp:
        description: Day(unix) we checked the status of the data
        type: integer
    type: object
  uiapi.procError:
    properties:
      stderr:
        description: String containing the standard error of the process.
        type: string
      stdout:
        description: String containing the standard output of the process.
        type: string
    type: object
  uiapi.timestamp:
    properties:
      nanos:
        type: integer
      seconds:
        type: integer
    type: object
  uiapi.v2AgencyTotalsYear:
    properties:
      ano:
        type: integer
      meses:
        items:
          $ref: '#/definitions/uiapi.v2MonthTotals'
        type: array
      orgao:
        $ref: '#/definitions/uiapi.agency'
      package:
        $ref: '#/definitions/uiapi.backup'
    type: object
  uiapi.v2MonthTotals:
    properties:
      error:
        $ref: '#/definitions/uiapi.procError'
      mes:
        type: integer
      outras_remuneracoes:
        type: number
      remuneracao_base:
        type: number
      timestamp:
        $ref: '#/definitions/uiapi.timestamp'
      total_membros:
        type: integer
    type: object
info:
  contact:
    name: DadosJusBr
    url: https://dadosjusbr.org
  title: API do dadosjusbr.org
  version: "1.0"
paths:
  /uiapi/v2/orgao/totais/{orgao}/{ano}:
    get:
      description: Busca os dados de remuneração de um órgão em um ano específico.
      operationId: GetTotalsOfAgencyYear
      parameters:
      - description: 'ID do órgão. Exemplos: tjal, tjba, mppb.'
        in: path
        name: orgao
        required: true
        type: string
      - description: 'Ano. Exemplo: 2018.'
        in: path
        name: ano
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/uiapi.v2AgencyTotalsYear'
        "400":
          description: Parâmetro ano ou orgao inválido.
          schema:
            type: string
      tags:
      - uiapi
  /v1/orgao/{orgao}:
    get:
      description: Busca um órgão específico utilizando seu ID.
      operationId: GetAgencyById
      parameters:
      - description: 'ID do órgão. Exemplos: tjal, tjba, mppb.'
        in: path
        name: orgao
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Requisição bem sucedida.
          schema:
            $ref: '#/definitions/papi.agency'
        "404":
          description: Órgão não encontrado.
          schema:
            type: string
swagger: "2.0"
